on: push

jobs:
  windows-tests:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Setup WSL
        uses: Vampire/setup-wsl@v2
        with:
          additional-packages: curl docker
          distribution: Ubuntu-20.04
      - name: Run Steps
        shell: wsl-bash_Ubuntu-20.04 {0}
        run: |
          echo "export GITHUB_TOKEN=${{ secrets.TOKEN }}" >> .env
          apt-get update -y
          apt-get install dos2unix
          apt install build-essential -y
 
          echo "Installing Scala"
          curl -fL https://github.com/coursier/coursier/releases/download/v2.1.0/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup -y &&  ./cs install giter8
          echo "Scala Installed"

      - name: Convert files dos2unix
        shell: wsl-bash_Ubuntu-20.04 {0}
        run: |
          dos2unix scripts/hydra
          dos2unix .env

      - name: Run Hydra
        shell: wsl-bash_Ubuntu-20.04 {0}
        run: |
          echo "Installing CARGO"
          curl https://sh.rustup.rs -sSf | sh -s -- -y 
          echo "Cargo Installed"

          source "$HOME/.cargo/env"
          
          echo "Installing ARGC"
          cargo install argc
          echo "ARGC Installed"
          
          scripts/hydra install

          scripts/hydra build

          scripts/hydra start_genesis

          scripts/hydra stop

          scripts/hydra destroy